
CREATE TYPE department_enum AS ENUM (
  'product',
  'frontend',
  'backend',
  'cloud'
);


CREATE TYPE level_enum AS ENUM (
  'entry',
  'junior',
  'mid_level',
  'senior'
);

CREATE TABLE employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL UNIQUE,
  phone_number VARCHAR(250) NOT NULL,
  address VARCHAR(250) NOT NULL,
  dob DATE NOT NULL,
  department department_enum NOT NULL,
  level level_enum NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON employees
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

